### ISSUE TITLE
Check existing TODO issues and see if valid

### ISSUE THREAD

**Issue by paulpeeling** [paulpeeling/mdevu#2]
- [ ] Trap suite errors
- [ ] push button run
- [ ] Restore Link Listener behaviour
- [ ] Check resizing behaviour (seems like R2015b broken)
- [ ] Use panels instead of empty boxes
